name: "Docs: Navigation Branch"

on:
  push:
    branches:
      - navigation

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: ros:humble

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: navigation

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3-pip
          python3 -m pip install 'git+https://github.com/ros-infrastructure/rosdoc2@main'
          pip install numpy
          rosdep update
          rosdep install --from-paths . -y --rosdistro humble

      - name: Build with rosdoc2
        run: |
          rosdoc2 build --package-path ticare_navigation

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_output/ticare_navigation
          publish_branch: gh-pages
